//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.nbrmService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.nbrm.mk/klservice/", ConfigurationName="nbrmService.KursSoap")]
    public interface KursSoap {
        
        // CODEGEN: Generating message contract since element name GetExchangeRateDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        WebApplication1.nbrmService.GetExchangeRateDResponse GetExchangeRateD(WebApplication1.nbrmService.GetExchangeRateDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRateDResponse> GetExchangeRateDAsync(WebApplication1.nbrmService.GetExchangeRateDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        WebApplication1.nbrmService.GetExchangeRateResponse GetExchangeRate(WebApplication1.nbrmService.GetExchangeRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRateResponse> GetExchangeRateAsync(WebApplication1.nbrmService.GetExchangeRateRequest request);
        
        // CODEGEN: Generating message contract since element name GetExchangeRatesDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        WebApplication1.nbrmService.GetExchangeRatesDResponse GetExchangeRatesD(WebApplication1.nbrmService.GetExchangeRatesDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRatesDResponse> GetExchangeRatesDAsync(WebApplication1.nbrmService.GetExchangeRatesDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        WebApplication1.nbrmService.GetExchangeRatesResponse GetExchangeRates(WebApplication1.nbrmService.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRatesResponse> GetExchangeRatesAsync(WebApplication1.nbrmService.GetExchangeRatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRateDRequestBody Body;
        
        public GetExchangeRateDRequest() {
        }
        
        public GetExchangeRateDRequest(WebApplication1.nbrmService.GetExchangeRateDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRateDRequestBody() {
        }
        
        public GetExchangeRateDRequestBody(System.DateTime StartDate, System.DateTime EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRateDResponseBody Body;
        
        public GetExchangeRateDResponse() {
        }
        
        public GetExchangeRateDResponse(WebApplication1.nbrmService.GetExchangeRateDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateDResult;
        
        public GetExchangeRateDResponseBody() {
        }
        
        public GetExchangeRateDResponseBody(string GetExchangeRateDResult) {
            this.GetExchangeRateDResult = GetExchangeRateDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRate", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRateRequestBody Body;
        
        public GetExchangeRateRequest() {
        }
        
        public GetExchangeRateRequest(WebApplication1.nbrmService.GetExchangeRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRateRequestBody() {
        }
        
        public GetExchangeRateRequestBody(string StartDate, string EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRateResponseBody Body;
        
        public GetExchangeRateResponse() {
        }
        
        public GetExchangeRateResponse(WebApplication1.nbrmService.GetExchangeRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateResult;
        
        public GetExchangeRateResponseBody() {
        }
        
        public GetExchangeRateResponseBody(string GetExchangeRateResult) {
            this.GetExchangeRateResult = GetExchangeRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRatesDRequestBody Body;
        
        public GetExchangeRatesDRequest() {
        }
        
        public GetExchangeRatesDRequest(WebApplication1.nbrmService.GetExchangeRatesDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRatesDRequestBody() {
        }
        
        public GetExchangeRatesDRequestBody(System.DateTime StartDate, System.DateTime EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRatesDResponseBody Body;
        
        public GetExchangeRatesDResponse() {
        }
        
        public GetExchangeRatesDResponse(WebApplication1.nbrmService.GetExchangeRatesDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesDResult;
        
        public GetExchangeRatesDResponseBody() {
        }
        
        public GetExchangeRatesDResponseBody(string GetExchangeRatesDResult) {
            this.GetExchangeRatesDResult = GetExchangeRatesDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(WebApplication1.nbrmService.GetExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRatesRequestBody() {
        }
        
        public GetExchangeRatesRequestBody(string StartDate, string EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WebApplication1.nbrmService.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(WebApplication1.nbrmService.GetExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody() {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult) {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KursSoapChannel : WebApplication1.nbrmService.KursSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KursSoapClient : System.ServiceModel.ClientBase<WebApplication1.nbrmService.KursSoap>, WebApplication1.nbrmService.KursSoap {
        
        public KursSoapClient() {
        }
        
        public KursSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KursSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.nbrmService.GetExchangeRateDResponse WebApplication1.nbrmService.KursSoap.GetExchangeRateD(WebApplication1.nbrmService.GetExchangeRateDRequest request) {
            return base.Channel.GetExchangeRateD(request);
        }
        
        public string GetExchangeRateD(System.DateTime StartDate, System.DateTime EndDate) {
            WebApplication1.nbrmService.GetExchangeRateDRequest inValue = new WebApplication1.nbrmService.GetExchangeRateDRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WebApplication1.nbrmService.GetExchangeRateDResponse retVal = ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRateD(inValue);
            return retVal.Body.GetExchangeRateDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRateDResponse> WebApplication1.nbrmService.KursSoap.GetExchangeRateDAsync(WebApplication1.nbrmService.GetExchangeRateDRequest request) {
            return base.Channel.GetExchangeRateDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRateDResponse> GetExchangeRateDAsync(System.DateTime StartDate, System.DateTime EndDate) {
            WebApplication1.nbrmService.GetExchangeRateDRequest inValue = new WebApplication1.nbrmService.GetExchangeRateDRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRateDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.nbrmService.GetExchangeRateResponse WebApplication1.nbrmService.KursSoap.GetExchangeRate(WebApplication1.nbrmService.GetExchangeRateRequest request) {
            return base.Channel.GetExchangeRate(request);
        }
        
        public string GetExchangeRate(string StartDate, string EndDate) {
            WebApplication1.nbrmService.GetExchangeRateRequest inValue = new WebApplication1.nbrmService.GetExchangeRateRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WebApplication1.nbrmService.GetExchangeRateResponse retVal = ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRate(inValue);
            return retVal.Body.GetExchangeRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRateResponse> WebApplication1.nbrmService.KursSoap.GetExchangeRateAsync(WebApplication1.nbrmService.GetExchangeRateRequest request) {
            return base.Channel.GetExchangeRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRateResponse> GetExchangeRateAsync(string StartDate, string EndDate) {
            WebApplication1.nbrmService.GetExchangeRateRequest inValue = new WebApplication1.nbrmService.GetExchangeRateRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.nbrmService.GetExchangeRatesDResponse WebApplication1.nbrmService.KursSoap.GetExchangeRatesD(WebApplication1.nbrmService.GetExchangeRatesDRequest request) {
            return base.Channel.GetExchangeRatesD(request);
        }
        
        public string GetExchangeRatesD(System.DateTime StartDate, System.DateTime EndDate) {
            WebApplication1.nbrmService.GetExchangeRatesDRequest inValue = new WebApplication1.nbrmService.GetExchangeRatesDRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WebApplication1.nbrmService.GetExchangeRatesDResponse retVal = ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRatesD(inValue);
            return retVal.Body.GetExchangeRatesDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRatesDResponse> WebApplication1.nbrmService.KursSoap.GetExchangeRatesDAsync(WebApplication1.nbrmService.GetExchangeRatesDRequest request) {
            return base.Channel.GetExchangeRatesDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRatesDResponse> GetExchangeRatesDAsync(System.DateTime StartDate, System.DateTime EndDate) {
            WebApplication1.nbrmService.GetExchangeRatesDRequest inValue = new WebApplication1.nbrmService.GetExchangeRatesDRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRatesDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.nbrmService.GetExchangeRatesResponse WebApplication1.nbrmService.KursSoap.GetExchangeRates(WebApplication1.nbrmService.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string StartDate, string EndDate) {
            WebApplication1.nbrmService.GetExchangeRatesRequest inValue = new WebApplication1.nbrmService.GetExchangeRatesRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WebApplication1.nbrmService.GetExchangeRatesResponse retVal = ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRatesResponse> WebApplication1.nbrmService.KursSoap.GetExchangeRatesAsync(WebApplication1.nbrmService.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.nbrmService.GetExchangeRatesResponse> GetExchangeRatesAsync(string StartDate, string EndDate) {
            WebApplication1.nbrmService.GetExchangeRatesRequest inValue = new WebApplication1.nbrmService.GetExchangeRatesRequest();
            inValue.Body = new WebApplication1.nbrmService.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WebApplication1.nbrmService.KursSoap)(this)).GetExchangeRatesAsync(inValue);
        }
    }
}
